import type { EditorProject } from "../types/editor";

export function createStarterProject(tabNumber = 1): EditorProject {
  return {
    name: `\u672a\u547d\u540d\u9875\u9762 ${tabNumber}`,
    canvas: {
      width: 1280,
      height: 820,
      background: "#ffffff",
    },
    elements: [
      {
        id: `text-title-${tabNumber}`,
        kind: "text",
        content: "Build Your Own HTML",
        style: {
          left: 82,
          top: 78,
          width: 420,
          height: 60,
          color: "#17355d",
          background: "#ffffff",
          borderColor: "#ffffff",
          borderRadius: 0,
          fontSize: 32,
          fontFamily: "\"Segoe UI\", \"PingFang SC\", sans-serif",
          zIndex: 2,
        },
      },
      {
        id: `text-subtitle-${tabNumber}`,
        kind: "text",
        content:
          "\u50cf\u753b\u56fe\u5de5\u5177\u4e00\u6837\u62d6\u52a8\u548c\u8bbe\u7f6e\u9875\u9762\u5143\u7d20",
        style: {
          left: 84,
          top: 152,
          width: 360,
          height: 42,
          color: "#4f6485",
          background: "#ffffff",
          borderColor: "#ffffff",
          borderRadius: 0,
          fontSize: 18,
          fontFamily: "\"Segoe UI\", \"PingFang SC\", sans-serif",
          zIndex: 2,
        },
      },
      {
        id: `image-hero-${tabNumber}`,
        kind: "image",
        content: "\u793a\u4f8b\u56fe\u7247",
        imageSrc: "/placeholder.svg",
        style: {
          left: 780,
          top: 86,
          width: 320,
          height: 214,
          color: "#17355d",
          background: "#edf3fb",
          borderColor: "#c3d7f3",
          borderRadius: 24,
          fontSize: 16,
          fontFamily: "\"Segoe UI\", \"PingFang SC\", sans-serif",
          zIndex: 1,
        },
      },
      {
        id: `button-cta-${tabNumber}`,
        kind: "button",
        content: "\u5f00\u59cb\u7f16\u8f91",
        style: {
          left: 86,
          top: 240,
          width: 170,
          height: 54,
          color: "#16365f",
          background: "#d8e7ff",
          borderColor: "#a4c0ec",
          borderRadius: 18,
          fontSize: 18,
          fontFamily: "\"Segoe UI\", \"PingFang SC\", sans-serif",
          zIndex: 2,
        },
      },
      {
        id: `container-card-${tabNumber}`,
        kind: "container",
        content: "\u5c5e\u6027\u533a\u5757",
        style: {
          left: 86,
          top: 350,
          width: 460,
          height: 200,
          color: "#17355d",
          background: "#f5f8fd",
          borderColor: "#d0def4",
          borderRadius: 24,
          fontSize: 20,
          fontFamily: "\"Segoe UI\", \"PingFang SC\", sans-serif",
          zIndex: 1,
        },
      },
    ],
  };
}
